### ISSUE TITLE
XPF currency not supported

### ISSUE THREAD

**Issue by rahilwazir** [lyra/plugin-woocommerce#1]
WooCommerce does not support XPF currency, hence this plugin prompts with the following error when redirected to the epaync gateway.

![image](https://user-images.githubusercontent.com/1818941/94907555-c70e5c00-04b9-11eb-950d-3575ccf24537.png)

The merchant has configured their store to accept XPF currency.

**Comment by nabil509** [comment]
From this error screen, the currency sent here is 840 - USD. It is not supported by EpayNC gateway.

Please do not install directly the source code from this repository. Download the EpayNC plugin package from https://github.com/lyra/plugin-woocommerce/releases to get a plugin customized for EpayNC gateway.

Let me know if your problem is resolved, please.

**Comment by rahilwazir** [comment]
@nabil509 Thanks for your reply.

I installed the plugin *EpayNC_WooCommerce_2.x-4.x_v1.8.5.zip* from the releases page. Although the issue persists with the same error as reported above.

WooCommerce does not have XPF currency for it's store configuration hence I can't use the same currency (XPF) as configured on the EpayNC.

Does it make sense?

I'm not sure, but since EpayNC supports XPF currency, the payment plugin should add currency support to WooCommerce via one of their hooks `woocommerce_currencies`.

**Comment by rahilwazir** [comment]
Nevermind the currency is supported naming CFP in the list. Thanks
