### ISSUE TITLE
Suggestions on enhancement : multi payment

### ISSUE THREAD

**Issue by benjamin-schneider** [lyra/plugin-woocommerce#5]
We had an unwanted behaviour while using the multi payment. With the period set to "30", there is a gap month after month.

Let me show you a concrete example, because il will be easier to figure it out this way.

A customer wants to pay in 4 steps, we are the (Y-m-d) 2023-01-13. This result to this sequence (french dates, d-m-Y sorry about that) :

Echéance | Date de vente | Montant
-- | -- | --
1 | 13/01/2023 | 787,50 EUR
2 | 12/02/2023 | 787,50 EUR
3 | 14/03/2023 | 787,50 EUR
4 | 13/04/2023 | 787,50 EUR

The day are not perfectly aligned, which is still acceptable. 

Now imagine you are the 2023-01-31 Januray the next period will skip Februar, which is - in our point of view - not acceptable (the user opt in to pay every month).

I did a fix for that which overloads the whole `PayzenRequest`class in a mu-plugin. I know this is a bit dirty but it was the last chance to change this behaviour without directly modifying the plugin directly.

My questions are :
- do you consider this behaviour as a bug ?
- is there a way to overload setMultiPayment in a "standard" way ?

My suggestions 
Use a MULTI_EXT payment config and compute periods to increment month by month.

**Comment by nberhouche** [comment]
Hello Benjamin

Thank you your feedback. We do not consider the aforementioned behavior as a bug, since the description of the field and the module documentation clearly state that the interval is in days (not months or weeks).
But we understand that having the installments set to specific dates and/or on a monthly basis would be more convenient for buyers. However implenting MULTI_EXT (See https://payzen.io/en-EN/form-payment/reference/vads-payment-config.html, for more info)  in the module would be a complex and rather specific (And our module aim to be generic) , and we didn't receive any request about it - until you.

So, we are not planning on implenting MULTI_EXT in the short term, but we are still open to your suggestions/critics.

Best regards.

**Comment by benjamin-schneider** [comment]
Thanks for your answer, I agree with your point of view and understand that the module has to be kept as generic as possible.
It was not a crazy effort to implement that on project level. 
Regards
